### ISSUE TITLE
Characterize the resource requirements for downloading / installing / querying EnsemblLite data

### ISSUE THREAD

**Issue by khiron** [cogent3/SMBE2024Workshop#8]
using the following EnsemblLite configuration 

```
[remote path]
host=ftp.ensembl.org
path=pub
[local path]
staging_path=apes_112/download_112
install_path=apes_112/install_112
[release]
release=112
[Human]
db=core
[Chimpanzee]
db=core
[Gorilla]
db=core
[compara]
align_names=10_primates.epo
homologies=
```

1. Download data from Ensembl `elt download -c apes_112.cfg`
2. Install the data `elt install -d apes_112/download_112 -np # -f` where # is number of processors to allocate
3. Sample one-to-one orthologs `elt homologs -i apes_112/install_112 --ref human --limit 20 -np # -o sampled-20`

Record time for each step, and memory consumption for step 2

**Comment by khiron** [comment]
In a 2 CPU 4GB container on Richard's home network with 92.0 Mbps download

Download: 336.11s
Install: 2344.99s memory consumption peaked at 4GB 
Sample: 18.28s

Container stats for the duration of all 3 processes 
- Download: 15:39 - 15:45
- Installation: 15:45 - 16:24
- Sampling: 16:24 - 16:25

![image](https://github.com/cogent3/SMBE2024Workshop/assets/1835007/d9fee2df-c50c-4e87-80d0-00bf56a78d61)

Log output

```
(c312) ➜  SMBE2024Workshop echo "Populating data..." && \
    cd /home/user/data && \
    /usr/bin/time -v elt download -c apes_112.cfg && \
    /usr/bin/time -v elt install -d apes_112/download_112 -np 2 -f && \
    /usr/bin/time -v elt homologs -i apes_112/install_112 --ref human --limit 20 -np 2 -o sampled-20
Populating data...
Downloaded to /home/user/data/apes_112/download_112
        Command being timed: "elt download -c apes_112.cfg"
        User time (seconds): 336.11
        System time (seconds): 1007.93
        Percent of CPU this job got: 58%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 38:28.58
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 587852
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 2380253
        Voluntary context switches: 7285308
        Involuntary context switches: 185761
        Swaps: 0
        File system inputs: 31834568
        File system outputs: 38057864
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
Installing features 📚 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:05:14
Installing  🧬🧬       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:-- 0:03:14Exception ignored in: <function Hdf5Mixin.__del__ at 0x7f6c51830860>
Traceback (most recent call last):
  File "/home/user/.conda/envs/c312/lib/python3.12/site-packages/ensembl_lite/_db_base.py", line 151, in __del__
    self._file.flush()
  File "/home/user/.conda/envs/c312/lib/python3.12/site-packages/h5py/_hl/files.py", line 590, in flush
    h5f.flush(self.id)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 159, in h5py.h5f.flush
Installing features 📚 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:05:14
Installing  🧬🧬       ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━  33% -:--:-- 0:04:29Exception ignored in: <function Hdf5Mixin.__del__ at 0x7f91bda30860>
Traceback (most recent call last):
  File "/home/user/.conda/envs/c312/lib/python3.12/site-packages/ensembl_lite/_db_base.py", line 151, in __del__
    self._file.flush()
  File "/home/user/.conda/envs/c312/lib/python3.12/site-packages/h5py/_hl/files.py", line 590, in flush
    h5f.flush(self.id)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 159, in h5py.h5f.flush
Installing features 📚 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:05:14
Installing  🧬🧬       ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━  67% -:--:-- 0:05:49Exception ignored in: <function Hdf5Mixin.__del__ at 0x7f6c51830860>
Traceback (most recent call last):
  File "/home/user/.conda/envs/c312/lib/python3.12/site-packages/ensembl_lite/_db_base.py", line 151, in __del__
    self._file.flush()
  File "/home/user/.conda/envs/c312/lib/python3.12/site-packages/h5py/_hl/files.py", line 590, in flush
    h5f.flush(self.id)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 159, in h5py.h5f.flush
Installing features 📚 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:05:14
Installing  🧬🧬       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:05:49
Installing homologies  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:01:03
Installing alignments  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:13:20
Contents installed to '/home/user/data/apes_112/install_112'
        Command being timed: "elt install -d apes_112/download_112 -np 2 -f"
        User time (seconds): 2344.99
        System time (seconds): 223.80
        Percent of CPU this job got: 153%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 27:58.85
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 2647432
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 39370
        Minor (reclaiming a frame) page faults: 5804645
        Voluntary context switches: 1717290
        Involuntary context switches: 222117
        Swaps: 0
        File system inputs: 40387408
        File system outputs: 18396920
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
Homolog search ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00
Extracting  🧬 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:12
        Command being timed: "elt homologs -i apes_112/install_112 --ref human --limit 20 -np 2 -o sampled-20"
        User time (seconds): 18.28
        System time (seconds): 5.77
        Percent of CPU this job got: 113%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:21.16
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 291248
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 163623
        Voluntary context switches: 18266
        Involuntary context switches: 15861
        Swaps: 0
        File system inputs: 2025296
        File system outputs: 416
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

**Comment by khiron** [comment]
MacBook using Colima to host container, allocated 4 processors, and using ANU'S internet

- Download: 109s
- Install: TBD
- Sample: TBD

```
(c312) ➜  data /usr/bin/time -v elt download -c /home/user/data/apes_112.cfg
Downloaded to /home/user/data/apes_112/download_112
        Command being timed: "elt download -c /home/user/data/apes_112.cfg"
        User time (seconds): 109.12
        System time (seconds): 253.31
        Percent of CPU this job got: 12%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 48:01.50
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 539200
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 1914
        Minor (reclaiming a frame) page faults: 4459396
        Voluntary context switches: 2584458
        Involuntary context switches: 38825
        Swaps: 0
        File system inputs: 32236720
        File system outputs: 38055856
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```
